/**
 * config-loader.ts
 * Loads and merges global + project-level config; fills auto placeholders
 * for literal rules; provides hot-reload subscription.
 *
 * Regex rules (type: "regex") are skipped here — their real values aren't
 * known until runtime, so masker.ts generates their placeholders lazily.
 */

import { readFile } from "node:fs/promises";
import { watch, type FSWatcher } from "node:fs";
import { join } from "node:path";
import { homedir } from "node:os";
import { CONFIG_DIR_NAME } from "@earendil-works/pi-coding-agent";
import { generatePlaceholder } from "./placeholder-gen.ts";
import { isRegexRule, type MaskingRule } from "./masker.ts";

// ─── Types ──────────────────────────────────────────────────────────────────

export interface MaskingOptions {
  /** Whether literal matching is case-sensitive (default true) */
  caseSensitive: boolean;
  /** Whether to show masking status in the bottom status bar (default true) */
  showStatusBar: boolean;
}

export interface MaskingConfig {
  enabled: boolean;
  rules: MaskingRule[];
  options: MaskingOptions;
}

export type { MaskingRule };

// ─── Paths ──────────────────────────────────────────────────────────────────

/** Pi user config root. Can be overridden by PI_CODING_AGENT_DIR. */
const AGENT_CONFIG_DIR = process.env.PI_CODING_AGENT_DIR ?? join(homedir(), ".pi", "agent");

/** Global config: ~/.pi/agent/pi-data-masking/masking.config.json */
export const GLOBAL_CONFIG_PATH = join(
  AGENT_CONFIG_DIR,
  "pi-data-masking",
  "masking.config.json"
);

/** Project-level config path: <cwd>/.pi/pi-data-masking/masking.config.json */
export function getProjectConfigPath(cwd: string): string {
  return join(cwd, CONFIG_DIR_NAME, "pi-data-masking", "masking.config.json");
}

// ─── Defaults ─────────────────────────────────────────────────────────────

function defaultConfig(): MaskingConfig {
  return {
    enabled: true,
    rules: [],
    options: {
      caseSensitive: true,
      showStatusBar: true,
    },
  };
}

// ─── File reading ───────────────────────────────────────────────────────────

async function tryReadJson(path: string): Promise<Partial<MaskingConfig> | null> {
  try {
    const raw = await readFile(path, "utf8");
    return JSON.parse(raw) as Partial<MaskingConfig>;
  } catch {
    return null;
  }
}

// ─── Merge logic ──────────────────────────────────────────────────────────

/**
 * Merge strategy:
 *  - rules: project-level rules first (higher priority), global rules appended after
 *  - options: project-level fields override global fields of the same name
 *  - enabled: project-level value wins if explicitly set, otherwise falls back to global
 */
function mergeConfigs(
  global: Partial<MaskingConfig> | null,
  project: Partial<MaskingConfig> | null
): MaskingConfig {
  const base = defaultConfig();

  const enabled =
    project?.enabled ?? global?.enabled ?? base.enabled;

  const rules = [
    ...(project?.rules ?? []),
    ...(global?.rules ?? []),
  ];

  const options: MaskingOptions = {
    ...base.options,
    ...(global?.options ?? {}),
    ...(project?.options ?? {}),
  };

  return { enabled, rules, options };
}

// ─── Placeholder filling ────────────────────────────────────────────────────

/**
 * For each literal rule, check its placeholder field:
 *  - missing or "auto" → generate via format-preserving replacement
 *  - explicit value     → use as-is (manual takes precedence)
 *
 * Regex rules (type: "regex") are skipped: they have no fixed real value,
 * so masker.ts generates their placeholders at runtime per match.
 *
 * sessionKey stays constant for the whole session, so the same real value
 * always gets the same placeholder — hot reload won't disturb existing
 * mappings.
 */
function fillPlaceholders(rules: MaskingRule[], sessionKey: Buffer): void {
  const seen = new Map<string, string>(); // real → placeholder, for dedup

  for (const rule of rules) {
    if (isRegexRule(rule)) continue;

    if (!rule.placeholder || rule.placeholder === "auto") {
      // Check whether this real value already got a placeholder this
      // session (can happen after merging global + project rules)
      if (seen.has(rule.real)) {
        rule.placeholder = seen.get(rule.real)!;
      } else {
        rule.placeholder = generatePlaceholder(rule.real, sessionKey);
        seen.set(rule.real, rule.placeholder);
      }
    }
  }
}

// ─── Main loader ──────────────────────────────────────────────────────────

/**
 * @param cwd        Current working directory, used to locate project config
 * @param sessionKey Session key, generated by index.ts on session_start and
 *                   passed in unchanged for the whole session (including hot reloads)
 */
export async function loadConfig(
  cwd: string,
  sessionKey: Buffer
): Promise<MaskingConfig> {
  const [globalData, projectData] = await Promise.all([
    tryReadJson(GLOBAL_CONFIG_PATH),
    tryReadJson(getProjectConfigPath(cwd)),
  ]);
  const config = mergeConfigs(globalData, projectData);
  fillPlaceholders(config.rules, sessionKey);
  return config;
}

// ─── File watching (hot reload) ────────────────────────────────────────────

/**
 * Watches both global and project-level config files, debounced 300ms
 * before calling onChange.
 * Returns a stop() function to call on session_shutdown.
 */
export function watchConfigs(cwd: string, onChange: () => void): () => void {
  const watchers: FSWatcher[] = [];
  let timer: ReturnType<typeof setTimeout> | null = null;

  function handleChange() {
    if (timer) clearTimeout(timer);
    timer = setTimeout(onChange, 300);
  }

  function tryWatch(path: string) {
    try {
      watchers.push(watch(path, handleChange));
    } catch {
      // Silently ignore if the file doesn't exist
    }
  }

  tryWatch(GLOBAL_CONFIG_PATH);
  tryWatch(getProjectConfigPath(cwd));

  return () => {
    if (timer) clearTimeout(timer);
    watchers.forEach((w) => w.close());
  };
}
